name: gym_app
description: A Flutter project for Health2Offer Gym. Offering customers and
  trainers easy access to the services in their pocket.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.5.0
  carousel_slider: ^3.0.0
  charts_flutter: ^0.9.0
  cupertino_icons: ^1.0.0
  expandable: ^4.1.4
  flutter_luban: ^0.1.11
  fluttertoast: ^7.1.6
  font_awesome_flutter: ^8.11.0
  http: ^0.12.2
  image_picker: ^0.6.7+22
  intl: ^0.15.6
  percent_indicator: ^2.1.9+1
  provider: ^4.3.2+2
  qr_code_scanner: ^0.3.5
  shared_preferences: ^0.5.12+4
  smooth_star_rating: ^1.1.1
  timeago: ^3.0.2
  url_launcher: ^5.7.10
  youtube_player_flutter: ^7.0.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.2

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/team/
    - lib/assets/review/
    - lib/assets/slider/
    - lib/assets/partners/
    - lib/assets/transformation/
    - lib/assets/onboarding/

  fonts:
    - family: Custom
      fonts:
        - asset: lib/styles/icons/Custom.ttf
