name: gym_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
# -------------Dependency Packages--------------
  font_awesome_flutter: ^8.11.0
  flutter_zoom_drawer: ^1.0.4+1
# ----------------------------------------------
cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
# -----------Dev Dependency Packages------------

# ----------------------------------------------

flutter:

  uses-material-design: true

# -----------------Asset Images-----------------
  assets:
    - lib/assets/images/  

# ----------------------------------------------

# -----------------Asset Fonts------------------
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Medium.ttf
# ----------------------------------------------